export const products = [
  {
    id: 1,
    name: 'Худи oversize черный',
    origin: 'Бишкек',
    article: 'HD-001-BK',
    specs: 'Футер 80/20, 330 г/м², карман-кенгуру',
    sizes: 'S–5XL, удлиненная спина',
    price: 6.5,
    bulkPrice: 5.9,
    bulkQty: 500,
    stock: '1500 шт',
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=800&auto=format&fit=crop',
    status: 'В наличии',
    description: 'Идеальное базовое худи свободного кроя. Выполнено из качественного футера с начесом. Сохраняет форму после многочисленных стирок. Подходит для нанесения принтов и вышивки.'
  },
  {
    id: 2,
    name: 'Худи с капюшоном серый',
    origin: 'Бишкек',
    article: 'HD-002-GR',
    specs: 'Хлопок 100%, реглан, шнурки',
    sizes: 'XS–3XL, принт возможен',
    price: 7.0,
    bulkPrice: 6.3,
    bulkQty: 500,
    stock: '10 дней',
    image: 'https://images.unsplash.com/photo-1564557287817-3785e38ec1f5?q=80&w=800&auto=format&fit=crop',
    status: 'Под заказ',
    description: 'Классическая модель с глубоким капюшоном. Натуральный хлопок обеспечивает комфорт в течение всего дня. Реглан-рукав не стесняет движений.'
  },
  {
    id: 3,
    name: 'Худи вязаный бежевый',
    origin: 'Китай',
    article: 'HD-003-BE',
    specs: 'Крупная вязка, экопряжа',
    sizes: 'M–XXL, тренд 2026',
    price: 8.5,
    bulkPrice: 7.7,
    bulkQty: 300,
    stock: '20 дней',
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=800&auto=format&fit=crop',
    status: 'Под заказ',
    description: 'Трендовая модель крупной вязки. Эко-пряжа премиального качества. Отлично подходит для создания уютных зимних образов.'
  },
  {
    id: 4,
    name: 'Худи унисекс белый',
    origin: 'Бишкек',
    article: 'HD-004-WH',
    specs: 'Двойная манжета, для HoReCa',
    sizes: 'S–4XL, усиленные швы',
    price: 6.8,
    bulkPrice: 6.1,
    bulkQty: 500,
    stock: '800 шт',
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=800&auto=format&fit=crop',
    status: 'В наличии',
    description: 'Белоснежное худи с усиленными швами. Разработано специально для интенсивного использования в сфере гостеприимства и корпоративного мерча.'
  },
  {
    id: 5,
    name: 'Худи slim-fit синий',
    origin: 'Бишкек',
    article: 'HD-005-BL',
    specs: 'Интерлок, без капюшона',
    sizes: 'S–XXL, спортивный крой',
    price: 6.2,
    bulkPrice: 5.6,
    bulkQty: 500,
    stock: '1200 шт',
    image: 'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?q=80&w=800&auto=format&fit=crop',
    status: 'В наличии',
    description: 'Спортивная модель приталенного кроя. Ткань интерлок отлично отводит влагу. Идеально для активного отдыха и занятий спортом.'
  },
  {
    id: 6,
    name: 'Худи с принтом черный',
    origin: 'Бишкек',
    article: 'HD-006-BK',
    specs: 'Футер, DTF-принт спереди',
    sizes: 'M–4XL, мерч-вариант',
    price: 7.2,
    bulkPrice: 6.5,
    bulkQty: 500,
    stock: '10 дней',
    image: 'https://images.unsplash.com/photo-1554568218-0f1715e72254?q=80&w=800&auto=format&fit=crop',
    status: 'Под заказ',
    description: 'Готовое решение для мерча. Качественный DTF-принт устойчив к стиркам. Плотный футер премиум-класса.'
  },
  {
    id: 7,
    name: 'Худи оверсайз меланж',
    origin: 'Китай',
    article: 'HD-007-ME',
    specs: 'Вязка меланж, капюшон',
    sizes: 'L–5XL, уличный стиль',
    price: 8.0,
    bulkPrice: 7.2,
    bulkQty: 300,
    stock: '20 дней',
    image: 'https://images.unsplash.com/photo-1513789172139-c1f25c0bc8e8?q=80&w=800&auto=format&fit=crop',
    status: 'Под заказ',
    description: 'Объемное худи из меланжевой ткани. Уникальная текстура и свободный крой. Популярный выбор для брендов уличной моды.'
  },
  {
    id: 8,
    name: 'Худи классика зеленый',
    origin: 'Бишкек',
    article: 'HD-008-GR',
    specs: 'Хлопок, карман-кенгуру',
    sizes: 'S–3XL, базовый вариант',
    price: 6.7,
    bulkPrice: 6.0,
    bulkQty: 500,
    stock: '2000 шт',
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=800&auto=format&fit=crop',
    status: 'В наличии',
    description: 'Классическое худи в насыщенном зеленом цвете. Традиционный карман-кенгуру и эластичные манжеты. База любого гардероба.'
  }
];
